### ISSUE TITLE
Issues installing TransitCenter repo

### ISSUE THREAD

**Issue by gabbyaz** [diluisi/TransitCenter#1]
Hi there - I am a newbie to GitHub and only a Python novice, so please excuse me if this is the wrong place to ask this. Should `setup.py` file in `master` be blank? I'm having some issues with install, and after looking through stack overflow / testing installs of other GitHub repos using the same method, I'm wondering if the blank `setup.py` might be the issue with my install. 

Thanks in advance for any info you can provide on the `setup.py` file - I appreciate it!

**Comment by diluisi** [comment]
Hi,

Thank you for your interest in the TransitCenter repo.

The project is not in the python package format. Actually, the code
reflects the architecture describe on README.md

Because we handled large datasets, it was not possible to upload them due
to Github storage constraints. The idea is to copy the code and simulate
the architecture as recommended in the repo.

Do you have a similar project to implement? Share your ideas, I will be
glad to collaborate with you.

Regards,

Diego

**Comment by gabbyaz** [comment]
Hi Diego,

Thank you so much for your response -- that makes sense. I am working on an analysis looking to measure transit accessibility by time of day, but on the state level; I am still discussing feasibility and definitions of accessibility with a team, but will definitely reach out with ideas once we have a better sense of a game plan.

Thanks again, I really appreciate it!
